### ISSUE TITLE
Feature Request: Generate XML Attributes as well

### ISSUE THREAD

**Issue by martyglaubitz** [hzsweers/barber#10]
I don't know if AAPT supports plugins like javac does, but this'd be truely awesome!

**Comment by ZacSweers** [comment]
Do you mean generating the declarations in `attrs.xml`?

**Comment by martyglaubitz** [comment]
@hzsweers exactly

**Comment by ZacSweers** [comment]
I'm not sure that's possible, let alone something I'd want to do in the
library. Can you comment with a sample of how you'd expect it to look?

**Comment by martyglaubitz** [comment]
@hzsweers i will, just give me some time

**Comment by ZacSweers** [comment]
Any update? Otherwise I'm going to close this issue for now

**Comment by martyglaubitz** [comment]
@hzsweers well i haven't yet got any time to think about this
