### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by denley** [hzsweers/barber#4]
Currently, we can only annotate/style a class that is directly instantiated. It would useful to be able to maintain the extendability of custom `View` types.

The problem is that a class' generated `Barbershop` is not invoked by subclasses. When the parent class calls `Barber.style` it will find the subclass' `Barbershop` instead of its own, because `target.getClass` does not refer to its own class.

I don't see any clean fix for this, unfortunately. So perhaps it's something to discuss for now rather than fix immediately. It would probably require some change to the API, such as passing the `Class` as a parameter in the `Barber.style` method. We can't simply have a `Barbershop` look for its parent class' `Barbershop` because it won't know the correct styleable resource to pass.

**Comment by ZacSweers** [comment]
Hmm, this is a very good point. So are you talking about the case where the child class has a different set of attributes than the parent?

**Comment by denley** [comment]
Yes, exactly. The case where both a class and its parent class have @StyledAttr annotations.

Perhaps its not a very common use-case. I'm struggling to think of a real-world example.

**Comment by ZacSweers** [comment]
So it's perfectly fair. I've been testing, and it actually _almost_ works. The issue has to do with how Java's polymorphism works.

Say you have the following two classes:

``` java
class A {
    public A() {
        System.out.println(this.getName());
    }
}
```

``` java
class B extends A {
    public B() {
        System.out.println(this.getName());
    }
}
```

The output of creating a new instance of B is this:

```
B
B
```

Same applies to views. The constructor hierarchy is called, but the parent View's constructor passes an instance of the child View to `Barber`, who then proceeds to look up the child's generated `$$Barbershop` class.

I have an idea of how I can maybe get around this issue, I'll add this to the 1.1.1 milestone

**Comment by ZacSweers** [comment]
This is now live in the latest `1.1.0` release.
